C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapinner_prod (inner_prodf2pywrap, v1, v2)
      external inner_prod
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) inner_prodf2pywrap, inner_prod
      inner_prodf2pywrap = inner_prod(v1, v2)
      end

