/* File: remapmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed May 17 03:39:10 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *remap_error;
static PyObject *remap_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(remap_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = remap_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(main,MAIN)(double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC_US(inner_prod,INNER_PROD)(double*,double*,double*);
extern void F_FUNC_US(mid_pt_sphere,MID_PT_SPHERE)(double*,double*,double*);
extern void F_FUNC_US(get_unit_vect2,GET_UNIT_VECT2)(double*,double*,double*);
extern void F_FUNC_US(get_latlon_vector,GET_LATLON_VECTOR)(double*,double*,double*);
extern void F_FUNC_US(normalize_vect,NORMALIZE_VECT)(double*);
extern void F_FUNC_US(vect_cross,VECT_CROSS)(double*,double*,double*);
extern void F_FUNC(latlon2xyz,LATLON2XYZ)(double*,double*,int*);
extern void F_FUNC_US(mid_pt3_cart,MID_PT3_CART)(double*,double*,double*);
extern void F_FUNC_US(cart_to_latlon,CART_TO_LATLON)(int*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ main ************************************/
static char doc_f2py_rout_remap_main[] = "\
main(geolon_s,geolat_s,geolon_w,geolat_w,is,ie,js,je,u_s,v_s,u_w,v_w,ud,vd)\n\nWrapper for ``main``.\
\n\nParameters\n----------\n"
"geolon_s : input rank-2 array('d') with bounds (1820,1093)\n"
"geolat_s : input rank-2 array('d') with bounds (1820,1093)\n"
"geolon_w : input rank-2 array('d') with bounds (1821,1092)\n"
"geolat_w : input rank-2 array('d') with bounds (1821,1092)\n"
"is : input int\n"
"ie : input int\n"
"js : input int\n"
"je : input int\n"
"u_s : input rank-3 array('d') with bounds (1820,1093,66)\n"
"v_s : input rank-3 array('d') with bounds (1820,1093,66)\n"
"u_w : input rank-3 array('d') with bounds (1821,1092,66)\n"
"v_w : input rank-3 array('d') with bounds (1821,1092,66)\n"
"ud : in/output rank-3 array('d') with bounds (1820,1093,66)\n"
"vd : in/output rank-3 array('d') with bounds (1821,1092,66)";
/* extern void F_FUNC(main,MAIN)(double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_remap_main(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *geolon_s = NULL;
  npy_intp geolon_s_Dims[2] = {-1, -1};
  const int geolon_s_Rank = 2;
  PyArrayObject *capi_geolon_s_tmp = NULL;
  int capi_geolon_s_intent = 0;
  PyObject *geolon_s_capi = Py_None;
  double *geolat_s = NULL;
  npy_intp geolat_s_Dims[2] = {-1, -1};
  const int geolat_s_Rank = 2;
  PyArrayObject *capi_geolat_s_tmp = NULL;
  int capi_geolat_s_intent = 0;
  PyObject *geolat_s_capi = Py_None;
  double *geolon_w = NULL;
  npy_intp geolon_w_Dims[2] = {-1, -1};
  const int geolon_w_Rank = 2;
  PyArrayObject *capi_geolon_w_tmp = NULL;
  int capi_geolon_w_intent = 0;
  PyObject *geolon_w_capi = Py_None;
  double *geolat_w = NULL;
  npy_intp geolat_w_Dims[2] = {-1, -1};
  const int geolat_w_Rank = 2;
  PyArrayObject *capi_geolat_w_tmp = NULL;
  int capi_geolat_w_intent = 0;
  PyObject *geolat_w_capi = Py_None;
  int is = 0;
  PyObject *is_capi = Py_None;
  int ie = 0;
  PyObject *ie_capi = Py_None;
  int js = 0;
  PyObject *js_capi = Py_None;
  int je = 0;
  PyObject *je_capi = Py_None;
  double *u_s = NULL;
  npy_intp u_s_Dims[3] = {-1, -1, -1};
  const int u_s_Rank = 3;
  PyArrayObject *capi_u_s_tmp = NULL;
  int capi_u_s_intent = 0;
  PyObject *u_s_capi = Py_None;
  double *v_s = NULL;
  npy_intp v_s_Dims[3] = {-1, -1, -1};
  const int v_s_Rank = 3;
  PyArrayObject *capi_v_s_tmp = NULL;
  int capi_v_s_intent = 0;
  PyObject *v_s_capi = Py_None;
  double *u_w = NULL;
  npy_intp u_w_Dims[3] = {-1, -1, -1};
  const int u_w_Rank = 3;
  PyArrayObject *capi_u_w_tmp = NULL;
  int capi_u_w_intent = 0;
  PyObject *u_w_capi = Py_None;
  double *v_w = NULL;
  npy_intp v_w_Dims[3] = {-1, -1, -1};
  const int v_w_Rank = 3;
  PyArrayObject *capi_v_w_tmp = NULL;
  int capi_v_w_intent = 0;
  PyObject *v_w_capi = Py_None;
  double *ud = NULL;
  npy_intp ud_Dims[3] = {-1, -1, -1};
  const int ud_Rank = 3;
  PyArrayObject *capi_ud_tmp = NULL;
  int capi_ud_intent = 0;
  PyObject *ud_capi = Py_None;
  double *vd = NULL;
  npy_intp vd_Dims[3] = {-1, -1, -1};
  const int vd_Rank = 3;
  PyArrayObject *capi_vd_tmp = NULL;
  int capi_vd_intent = 0;
  PyObject *vd_capi = Py_None;
    static char *capi_kwlist[] = {"geolon_s","geolat_s","geolon_w","geolat_w","is","ie","js","je","u_s","v_s","u_w","v_w","ud","vd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOO|:remap.main",\
        capi_kwlist,&geolon_s_capi,&geolat_s_capi,&geolon_w_capi,&geolat_w_capi,&is_capi,&ie_capi,&js_capi,&je_capi,&u_s_capi,&v_s_capi,&u_w_capi,&v_w_capi,&ud_capi,&vd_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable geolon_s */
  geolon_s_Dims[0]=1820,geolon_s_Dims[1]=1093;
  capi_geolon_s_intent |= F2PY_INTENT_IN;
  capi_geolon_s_tmp = array_from_pyobj(NPY_DOUBLE,geolon_s_Dims,geolon_s_Rank,capi_geolon_s_intent,geolon_s_capi);
  if (capi_geolon_s_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `geolon_s' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    geolon_s = (double *)(PyArray_DATA(capi_geolon_s_tmp));

  /* Processing variable geolat_s */
  geolat_s_Dims[0]=1820,geolat_s_Dims[1]=1093;
  capi_geolat_s_intent |= F2PY_INTENT_IN;
  capi_geolat_s_tmp = array_from_pyobj(NPY_DOUBLE,geolat_s_Dims,geolat_s_Rank,capi_geolat_s_intent,geolat_s_capi);
  if (capi_geolat_s_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `geolat_s' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    geolat_s = (double *)(PyArray_DATA(capi_geolat_s_tmp));

  /* Processing variable u_s */
  u_s_Dims[0]=1820,u_s_Dims[1]=1093,u_s_Dims[2]=66;
  capi_u_s_intent |= F2PY_INTENT_IN;
  capi_u_s_tmp = array_from_pyobj(NPY_DOUBLE,u_s_Dims,u_s_Rank,capi_u_s_intent,u_s_capi);
  if (capi_u_s_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 9th argument `u_s' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    u_s = (double *)(PyArray_DATA(capi_u_s_tmp));

  /* Processing variable v_s */
  v_s_Dims[0]=1820,v_s_Dims[1]=1093,v_s_Dims[2]=66;
  capi_v_s_intent |= F2PY_INTENT_IN;
  capi_v_s_tmp = array_from_pyobj(NPY_DOUBLE,v_s_Dims,v_s_Rank,capi_v_s_intent,v_s_capi);
  if (capi_v_s_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 10th argument `v_s' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    v_s = (double *)(PyArray_DATA(capi_v_s_tmp));

  /* Processing variable ud */
  ud_Dims[0]=1820,ud_Dims[1]=1093,ud_Dims[2]=66;
  capi_ud_intent |= F2PY_INTENT_INOUT;
  capi_ud_tmp = array_from_pyobj(NPY_DOUBLE,ud_Dims,ud_Rank,capi_ud_intent,ud_capi);
  if (capi_ud_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 13rd argument `ud' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    ud = (double *)(PyArray_DATA(capi_ud_tmp));

  /* Processing variable geolon_w */
  geolon_w_Dims[0]=1821,geolon_w_Dims[1]=1092;
  capi_geolon_w_intent |= F2PY_INTENT_IN;
  capi_geolon_w_tmp = array_from_pyobj(NPY_DOUBLE,geolon_w_Dims,geolon_w_Rank,capi_geolon_w_intent,geolon_w_capi);
  if (capi_geolon_w_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 3rd argument `geolon_w' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    geolon_w = (double *)(PyArray_DATA(capi_geolon_w_tmp));

  /* Processing variable geolat_w */
  geolat_w_Dims[0]=1821,geolat_w_Dims[1]=1092;
  capi_geolat_w_intent |= F2PY_INTENT_IN;
  capi_geolat_w_tmp = array_from_pyobj(NPY_DOUBLE,geolat_w_Dims,geolat_w_Rank,capi_geolat_w_intent,geolat_w_capi);
  if (capi_geolat_w_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 4th argument `geolat_w' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    geolat_w = (double *)(PyArray_DATA(capi_geolat_w_tmp));

  /* Processing variable u_w */
  u_w_Dims[0]=1821,u_w_Dims[1]=1092,u_w_Dims[2]=66;
  capi_u_w_intent |= F2PY_INTENT_IN;
  capi_u_w_tmp = array_from_pyobj(NPY_DOUBLE,u_w_Dims,u_w_Rank,capi_u_w_intent,u_w_capi);
  if (capi_u_w_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 11st argument `u_w' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    u_w = (double *)(PyArray_DATA(capi_u_w_tmp));

  /* Processing variable v_w */
  v_w_Dims[0]=1821,v_w_Dims[1]=1092,v_w_Dims[2]=66;
  capi_v_w_intent |= F2PY_INTENT_IN;
  capi_v_w_tmp = array_from_pyobj(NPY_DOUBLE,v_w_Dims,v_w_Rank,capi_v_w_intent,v_w_capi);
  if (capi_v_w_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 12nd argument `v_w' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    v_w = (double *)(PyArray_DATA(capi_v_w_tmp));

  /* Processing variable vd */
  vd_Dims[0]=1821,vd_Dims[1]=1092,vd_Dims[2]=66;
  capi_vd_intent |= F2PY_INTENT_INOUT;
  capi_vd_tmp = array_from_pyobj(NPY_DOUBLE,vd_Dims,vd_Rank,capi_vd_intent,vd_capi);
  if (capi_vd_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 14th argument `vd' of remap.main to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    vd = (double *)(PyArray_DATA(capi_vd_tmp));

  /* Processing variable is */
    f2py_success = int_from_pyobj(&is,is_capi,"remap.main() 5th argument (is) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ie */
    f2py_success = int_from_pyobj(&ie,ie_capi,"remap.main() 6th argument (ie) can't be converted to int");
  if (f2py_success) {
  /* Processing variable js */
    f2py_success = int_from_pyobj(&js,js_capi,"remap.main() 7th argument (js) can't be converted to int");
  if (f2py_success) {
  /* Processing variable je */
    f2py_success = int_from_pyobj(&je,je_capi,"remap.main() 8th argument (je) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(geolon_s,geolat_s,geolon_w,geolat_w,&is,&ie,&js,&je,u_s,v_s,u_w,v_w,ud,vd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of je*/
  /* End of cleaning variable je */
  } /*if (f2py_success) of js*/
  /* End of cleaning variable js */
  } /*if (f2py_success) of ie*/
  /* End of cleaning variable ie */
  } /*if (f2py_success) of is*/
  /* End of cleaning variable is */
  if((PyObject *)capi_vd_tmp!=vd_capi) {
    Py_XDECREF(capi_vd_tmp); }
  }  /*if (capi_vd_tmp == NULL) ... else of vd*/
  /* End of cleaning variable vd */
  if((PyObject *)capi_v_w_tmp!=v_w_capi) {
    Py_XDECREF(capi_v_w_tmp); }
  }  /*if (capi_v_w_tmp == NULL) ... else of v_w*/
  /* End of cleaning variable v_w */
  if((PyObject *)capi_u_w_tmp!=u_w_capi) {
    Py_XDECREF(capi_u_w_tmp); }
  }  /*if (capi_u_w_tmp == NULL) ... else of u_w*/
  /* End of cleaning variable u_w */
  if((PyObject *)capi_geolat_w_tmp!=geolat_w_capi) {
    Py_XDECREF(capi_geolat_w_tmp); }
  }  /*if (capi_geolat_w_tmp == NULL) ... else of geolat_w*/
  /* End of cleaning variable geolat_w */
  if((PyObject *)capi_geolon_w_tmp!=geolon_w_capi) {
    Py_XDECREF(capi_geolon_w_tmp); }
  }  /*if (capi_geolon_w_tmp == NULL) ... else of geolon_w*/
  /* End of cleaning variable geolon_w */
  if((PyObject *)capi_ud_tmp!=ud_capi) {
    Py_XDECREF(capi_ud_tmp); }
  }  /*if (capi_ud_tmp == NULL) ... else of ud*/
  /* End of cleaning variable ud */
  if((PyObject *)capi_v_s_tmp!=v_s_capi) {
    Py_XDECREF(capi_v_s_tmp); }
  }  /*if (capi_v_s_tmp == NULL) ... else of v_s*/
  /* End of cleaning variable v_s */
  if((PyObject *)capi_u_s_tmp!=u_s_capi) {
    Py_XDECREF(capi_u_s_tmp); }
  }  /*if (capi_u_s_tmp == NULL) ... else of u_s*/
  /* End of cleaning variable u_s */
  if((PyObject *)capi_geolat_s_tmp!=geolat_s_capi) {
    Py_XDECREF(capi_geolat_s_tmp); }
  }  /*if (capi_geolat_s_tmp == NULL) ... else of geolat_s*/
  /* End of cleaning variable geolat_s */
  if((PyObject *)capi_geolon_s_tmp!=geolon_s_capi) {
    Py_XDECREF(capi_geolon_s_tmp); }
  }  /*if (capi_geolon_s_tmp == NULL) ... else of geolon_s*/
  /* End of cleaning variable geolon_s */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of main ********************************/

/********************************* inner_prod *********************************/
static char doc_f2py_rout_remap_inner_prod[] = "\
inner_prod = inner_prod(v1,v2)\n\nWrapper for ``inner_prod``.\
\n\nParameters\n----------\n"
"v1 : input rank-1 array('d') with bounds (3)\n"
"v2 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"inner_prod : float";
/* extern void F_WRAPPEDFUNC_US(inner_prod,INNER_PROD)(double*,double*,double*); */
static PyObject *f2py_rout_remap_inner_prod(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double inner_prod = 0;
  double *v1 = NULL;
  npy_intp v1_Dims[1] = {-1};
  const int v1_Rank = 1;
  PyArrayObject *capi_v1_tmp = NULL;
  int capi_v1_intent = 0;
  PyObject *v1_capi = Py_None;
  double *v2 = NULL;
  npy_intp v2_Dims[1] = {-1};
  const int v2_Rank = 1;
  PyArrayObject *capi_v2_tmp = NULL;
  int capi_v2_intent = 0;
  PyObject *v2_capi = Py_None;
    static char *capi_kwlist[] = {"v1","v2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:remap.inner_prod",\
        capi_kwlist,&v1_capi,&v2_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable inner_prod */
  /* Processing variable v1 */
  v1_Dims[0]=3;
  capi_v1_intent |= F2PY_INTENT_IN;
  capi_v1_tmp = array_from_pyobj(NPY_DOUBLE,v1_Dims,v1_Rank,capi_v1_intent,v1_capi);
  if (capi_v1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `v1' of remap.inner_prod to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    v1 = (double *)(PyArray_DATA(capi_v1_tmp));

  /* Processing variable v2 */
  v2_Dims[0]=3;
  capi_v2_intent |= F2PY_INTENT_IN;
  capi_v2_tmp = array_from_pyobj(NPY_DOUBLE,v2_Dims,v2_Rank,capi_v2_intent,v2_capi);
  if (capi_v2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `v2' of remap.inner_prod to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    v2 = (double *)(PyArray_DATA(capi_v2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&inner_prod,v1,v2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",inner_prod);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_v2_tmp!=v2_capi) {
    Py_XDECREF(capi_v2_tmp); }
  }  /*if (capi_v2_tmp == NULL) ... else of v2*/
  /* End of cleaning variable v2 */
  if((PyObject *)capi_v1_tmp!=v1_capi) {
    Py_XDECREF(capi_v1_tmp); }
  }  /*if (capi_v1_tmp == NULL) ... else of v1*/
  /* End of cleaning variable v1 */
  /* End of cleaning variable inner_prod */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of inner_prod *****************************/

/******************************* mid_pt_sphere *******************************/
static char doc_f2py_rout_remap_mid_pt_sphere[] = "\
pm = mid_pt_sphere(p1,p2)\n\nWrapper for ``mid_pt_sphere``.\
\n\nParameters\n----------\n"
"p1 : input rank-1 array('d') with bounds (2)\n"
"p2 : input rank-1 array('d') with bounds (2)\n"
"\nReturns\n-------\n"
"pm : rank-1 array('d') with bounds (2)";
/* extern void F_FUNC_US(mid_pt_sphere,MID_PT_SPHERE)(double*,double*,double*); */
static PyObject *f2py_rout_remap_mid_pt_sphere(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *p1 = NULL;
  npy_intp p1_Dims[1] = {-1};
  const int p1_Rank = 1;
  PyArrayObject *capi_p1_tmp = NULL;
  int capi_p1_intent = 0;
  PyObject *p1_capi = Py_None;
  double *p2 = NULL;
  npy_intp p2_Dims[1] = {-1};
  const int p2_Rank = 1;
  PyArrayObject *capi_p2_tmp = NULL;
  int capi_p2_intent = 0;
  PyObject *p2_capi = Py_None;
  double *pm = NULL;
  npy_intp pm_Dims[1] = {-1};
  const int pm_Rank = 1;
  PyArrayObject *capi_pm_tmp = NULL;
  int capi_pm_intent = 0;
    static char *capi_kwlist[] = {"p1","p2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:remap.mid_pt_sphere",\
        capi_kwlist,&p1_capi,&p2_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable p1 */
  p1_Dims[0]=2;
  capi_p1_intent |= F2PY_INTENT_IN;
  capi_p1_tmp = array_from_pyobj(NPY_DOUBLE,p1_Dims,p1_Rank,capi_p1_intent,p1_capi);
  if (capi_p1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `p1' of remap.mid_pt_sphere to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p1 = (double *)(PyArray_DATA(capi_p1_tmp));

  /* Processing variable p2 */
  p2_Dims[0]=2;
  capi_p2_intent |= F2PY_INTENT_IN;
  capi_p2_tmp = array_from_pyobj(NPY_DOUBLE,p2_Dims,p2_Rank,capi_p2_intent,p2_capi);
  if (capi_p2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `p2' of remap.mid_pt_sphere to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p2 = (double *)(PyArray_DATA(capi_p2_tmp));

  /* Processing variable pm */
  pm_Dims[0]=2;
  capi_pm_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_pm_tmp = array_from_pyobj(NPY_DOUBLE,pm_Dims,pm_Rank,capi_pm_intent,Py_None);
  if (capi_pm_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `pm' of remap.mid_pt_sphere to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    pm = (double *)(PyArray_DATA(capi_pm_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(p1,p2,pm);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_pm_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pm_tmp == NULL) ... else of pm*/
  /* End of cleaning variable pm */
  if((PyObject *)capi_p2_tmp!=p2_capi) {
    Py_XDECREF(capi_p2_tmp); }
  }  /*if (capi_p2_tmp == NULL) ... else of p2*/
  /* End of cleaning variable p2 */
  if((PyObject *)capi_p1_tmp!=p1_capi) {
    Py_XDECREF(capi_p1_tmp); }
  }  /*if (capi_p1_tmp == NULL) ... else of p1*/
  /* End of cleaning variable p1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of mid_pt_sphere ****************************/

/******************************* get_unit_vect2 *******************************/
static char doc_f2py_rout_remap_get_unit_vect2[] = "\
uc = get_unit_vect2(e1,e2)\n\nWrapper for ``get_unit_vect2``.\
\n\nParameters\n----------\n"
"e1 : input rank-1 array('d') with bounds (2)\n"
"e2 : input rank-1 array('d') with bounds (2)\n"
"\nReturns\n-------\n"
"uc : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(get_unit_vect2,GET_UNIT_VECT2)(double*,double*,double*); */
static PyObject *f2py_rout_remap_get_unit_vect2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *e1 = NULL;
  npy_intp e1_Dims[1] = {-1};
  const int e1_Rank = 1;
  PyArrayObject *capi_e1_tmp = NULL;
  int capi_e1_intent = 0;
  PyObject *e1_capi = Py_None;
  double *e2 = NULL;
  npy_intp e2_Dims[1] = {-1};
  const int e2_Rank = 1;
  PyArrayObject *capi_e2_tmp = NULL;
  int capi_e2_intent = 0;
  PyObject *e2_capi = Py_None;
  double *uc = NULL;
  npy_intp uc_Dims[1] = {-1};
  const int uc_Rank = 1;
  PyArrayObject *capi_uc_tmp = NULL;
  int capi_uc_intent = 0;
    static char *capi_kwlist[] = {"e1","e2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:remap.get_unit_vect2",\
        capi_kwlist,&e1_capi,&e2_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable e1 */
  e1_Dims[0]=2;
  capi_e1_intent |= F2PY_INTENT_IN;
  capi_e1_tmp = array_from_pyobj(NPY_DOUBLE,e1_Dims,e1_Rank,capi_e1_intent,e1_capi);
  if (capi_e1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `e1' of remap.get_unit_vect2 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e1 = (double *)(PyArray_DATA(capi_e1_tmp));

  /* Processing variable e2 */
  e2_Dims[0]=2;
  capi_e2_intent |= F2PY_INTENT_IN;
  capi_e2_tmp = array_from_pyobj(NPY_DOUBLE,e2_Dims,e2_Rank,capi_e2_intent,e2_capi);
  if (capi_e2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `e2' of remap.get_unit_vect2 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e2 = (double *)(PyArray_DATA(capi_e2_tmp));

  /* Processing variable uc */
  uc_Dims[0]=3;
  capi_uc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_uc_tmp = array_from_pyobj(NPY_DOUBLE,uc_Dims,uc_Rank,capi_uc_intent,Py_None);
  if (capi_uc_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `uc' of remap.get_unit_vect2 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    uc = (double *)(PyArray_DATA(capi_uc_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(e1,e2,uc);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_uc_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_uc_tmp == NULL) ... else of uc*/
  /* End of cleaning variable uc */
  if((PyObject *)capi_e2_tmp!=e2_capi) {
    Py_XDECREF(capi_e2_tmp); }
  }  /*if (capi_e2_tmp == NULL) ... else of e2*/
  /* End of cleaning variable e2 */
  if((PyObject *)capi_e1_tmp!=e1_capi) {
    Py_XDECREF(capi_e1_tmp); }
  }  /*if (capi_e1_tmp == NULL) ... else of e1*/
  /* End of cleaning variable e1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of get_unit_vect2 ***************************/

/***************************** get_latlon_vector *****************************/
static char doc_f2py_rout_remap_get_latlon_vector[] = "\
elon,elat = get_latlon_vector(pp)\n\nWrapper for ``get_latlon_vector``.\
\n\nParameters\n----------\n"
"pp : input rank-1 array('d') with bounds (2)\n"
"\nReturns\n-------\n"
"elon : rank-1 array('d') with bounds (3)\n"
"elat : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(get_latlon_vector,GET_LATLON_VECTOR)(double*,double*,double*); */
static PyObject *f2py_rout_remap_get_latlon_vector(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *pp = NULL;
  npy_intp pp_Dims[1] = {-1};
  const int pp_Rank = 1;
  PyArrayObject *capi_pp_tmp = NULL;
  int capi_pp_intent = 0;
  PyObject *pp_capi = Py_None;
  double *elon = NULL;
  npy_intp elon_Dims[1] = {-1};
  const int elon_Rank = 1;
  PyArrayObject *capi_elon_tmp = NULL;
  int capi_elon_intent = 0;
  double *elat = NULL;
  npy_intp elat_Dims[1] = {-1};
  const int elat_Rank = 1;
  PyArrayObject *capi_elat_tmp = NULL;
  int capi_elat_intent = 0;
    static char *capi_kwlist[] = {"pp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:remap.get_latlon_vector",\
        capi_kwlist,&pp_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable pp */
  pp_Dims[0]=2;
  capi_pp_intent |= F2PY_INTENT_IN;
  capi_pp_tmp = array_from_pyobj(NPY_DOUBLE,pp_Dims,pp_Rank,capi_pp_intent,pp_capi);
  if (capi_pp_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `pp' of remap.get_latlon_vector to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    pp = (double *)(PyArray_DATA(capi_pp_tmp));

  /* Processing variable elon */
  elon_Dims[0]=3;
  capi_elon_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_elon_tmp = array_from_pyobj(NPY_DOUBLE,elon_Dims,elon_Rank,capi_elon_intent,Py_None);
  if (capi_elon_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `elon' of remap.get_latlon_vector to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    elon = (double *)(PyArray_DATA(capi_elon_tmp));

  /* Processing variable elat */
  elat_Dims[0]=3;
  capi_elat_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_elat_tmp = array_from_pyobj(NPY_DOUBLE,elat_Dims,elat_Rank,capi_elat_intent,Py_None);
  if (capi_elat_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `elat' of remap.get_latlon_vector to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    elat = (double *)(PyArray_DATA(capi_elat_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pp,elon,elat);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_elon_tmp,capi_elat_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_elat_tmp == NULL) ... else of elat*/
  /* End of cleaning variable elat */
  }  /*if (capi_elon_tmp == NULL) ... else of elon*/
  /* End of cleaning variable elon */
  if((PyObject *)capi_pp_tmp!=pp_capi) {
    Py_XDECREF(capi_pp_tmp); }
  }  /*if (capi_pp_tmp == NULL) ... else of pp*/
  /* End of cleaning variable pp */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of get_latlon_vector **************************/

/******************************* normalize_vect *******************************/
static char doc_f2py_rout_remap_normalize_vect[] = "\
normalize_vect(e)\n\nWrapper for ``normalize_vect``.\
\n\nParameters\n----------\n"
"e : in/output rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(normalize_vect,NORMALIZE_VECT)(double*); */
static PyObject *f2py_rout_remap_normalize_vect(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *e = NULL;
  npy_intp e_Dims[1] = {-1};
  const int e_Rank = 1;
  PyArrayObject *capi_e_tmp = NULL;
  int capi_e_intent = 0;
  PyObject *e_capi = Py_None;
    static char *capi_kwlist[] = {"e",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:remap.normalize_vect",\
        capi_kwlist,&e_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable e */
  e_Dims[0]=3;
  capi_e_intent |= F2PY_INTENT_INOUT;
  capi_e_tmp = array_from_pyobj(NPY_DOUBLE,e_Dims,e_Rank,capi_e_intent,e_capi);
  if (capi_e_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `e' of remap.normalize_vect to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e = (double *)(PyArray_DATA(capi_e_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(e);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_e_tmp!=e_capi) {
    Py_XDECREF(capi_e_tmp); }
  }  /*if (capi_e_tmp == NULL) ... else of e*/
  /* End of cleaning variable e */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of normalize_vect ***************************/

/********************************* vect_cross *********************************/
static char doc_f2py_rout_remap_vect_cross[] = "\
e = vect_cross(p1,p2)\n\nWrapper for ``vect_cross``.\
\n\nParameters\n----------\n"
"p1 : input rank-1 array('d') with bounds (3)\n"
"p2 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"e : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(vect_cross,VECT_CROSS)(double*,double*,double*); */
static PyObject *f2py_rout_remap_vect_cross(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *e = NULL;
  npy_intp e_Dims[1] = {-1};
  const int e_Rank = 1;
  PyArrayObject *capi_e_tmp = NULL;
  int capi_e_intent = 0;
  double *p1 = NULL;
  npy_intp p1_Dims[1] = {-1};
  const int p1_Rank = 1;
  PyArrayObject *capi_p1_tmp = NULL;
  int capi_p1_intent = 0;
  PyObject *p1_capi = Py_None;
  double *p2 = NULL;
  npy_intp p2_Dims[1] = {-1};
  const int p2_Rank = 1;
  PyArrayObject *capi_p2_tmp = NULL;
  int capi_p2_intent = 0;
  PyObject *p2_capi = Py_None;
    static char *capi_kwlist[] = {"p1","p2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:remap.vect_cross",\
        capi_kwlist,&p1_capi,&p2_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable p1 */
  p1_Dims[0]=3;
  capi_p1_intent |= F2PY_INTENT_IN;
  capi_p1_tmp = array_from_pyobj(NPY_DOUBLE,p1_Dims,p1_Rank,capi_p1_intent,p1_capi);
  if (capi_p1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `p1' of remap.vect_cross to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p1 = (double *)(PyArray_DATA(capi_p1_tmp));

  /* Processing variable p2 */
  p2_Dims[0]=3;
  capi_p2_intent |= F2PY_INTENT_IN;
  capi_p2_tmp = array_from_pyobj(NPY_DOUBLE,p2_Dims,p2_Rank,capi_p2_intent,p2_capi);
  if (capi_p2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `p2' of remap.vect_cross to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p2 = (double *)(PyArray_DATA(capi_p2_tmp));

  /* Processing variable e */
  e_Dims[0]=3;
  capi_e_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_e_tmp = array_from_pyobj(NPY_DOUBLE,e_Dims,e_Rank,capi_e_intent,Py_None);
  if (capi_e_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `e' of remap.vect_cross to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e = (double *)(PyArray_DATA(capi_e_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(e,p1,p2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_e_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_e_tmp == NULL) ... else of e*/
  /* End of cleaning variable e */
  if((PyObject *)capi_p2_tmp!=p2_capi) {
    Py_XDECREF(capi_p2_tmp); }
  }  /*if (capi_p2_tmp == NULL) ... else of p2*/
  /* End of cleaning variable p2 */
  if((PyObject *)capi_p1_tmp!=p1_capi) {
    Py_XDECREF(capi_p1_tmp); }
  }  /*if (capi_p1_tmp == NULL) ... else of p1*/
  /* End of cleaning variable p1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of vect_cross *****************************/

/********************************* latlon2xyz *********************************/
static char doc_f2py_rout_remap_latlon2xyz[] = "\
e = latlon2xyz(p,[id])\n\nWrapper for ``latlon2xyz``.\
\n\nParameters\n----------\n"
"p : input rank-1 array('d') with bounds (2)\n"
"\nOther Parameters\n----------------\n"
"id : input int\n"
"\nReturns\n-------\n"
"e : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC(latlon2xyz,LATLON2XYZ)(double*,double*,int*); */
static PyObject *f2py_rout_remap_latlon2xyz(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *p = NULL;
  npy_intp p_Dims[1] = {-1};
  const int p_Rank = 1;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  double *e = NULL;
  npy_intp e_Dims[1] = {-1};
  const int e_Rank = 1;
  PyArrayObject *capi_e_tmp = NULL;
  int capi_e_intent = 0;
  int id = 0;
  PyObject *id_capi = Py_None;
    static char *capi_kwlist[] = {"p","id",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|O:remap.latlon2xyz",\
        capi_kwlist,&p_capi,&id_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable p */
  p_Dims[0]=2;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_DOUBLE,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `p' of remap.latlon2xyz to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p = (double *)(PyArray_DATA(capi_p_tmp));

  /* Processing variable e */
  e_Dims[0]=3;
  capi_e_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_e_tmp = array_from_pyobj(NPY_DOUBLE,e_Dims,e_Rank,capi_e_intent,Py_None);
  if (capi_e_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `e' of remap.latlon2xyz to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e = (double *)(PyArray_DATA(capi_e_tmp));

  /* Processing variable id */
  if (id_capi != Py_None)
    f2py_success = int_from_pyobj(&id,id_capi,"remap.latlon2xyz() 1st keyword (id) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(p,e,&id);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_e_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of id*/
  /* End of cleaning variable id */
  }  /*if (capi_e_tmp == NULL) ... else of e*/
  /* End of cleaning variable e */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of latlon2xyz *****************************/

/******************************** mid_pt3_cart ********************************/
static char doc_f2py_rout_remap_mid_pt3_cart[] = "\
e = mid_pt3_cart(p1,p2)\n\nWrapper for ``mid_pt3_cart``.\
\n\nParameters\n----------\n"
"p1 : input rank-1 array('d') with bounds (3)\n"
"p2 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"e : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(mid_pt3_cart,MID_PT3_CART)(double*,double*,double*); */
static PyObject *f2py_rout_remap_mid_pt3_cart(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double *p1 = NULL;
  npy_intp p1_Dims[1] = {-1};
  const int p1_Rank = 1;
  PyArrayObject *capi_p1_tmp = NULL;
  int capi_p1_intent = 0;
  PyObject *p1_capi = Py_None;
  double *p2 = NULL;
  npy_intp p2_Dims[1] = {-1};
  const int p2_Rank = 1;
  PyArrayObject *capi_p2_tmp = NULL;
  int capi_p2_intent = 0;
  PyObject *p2_capi = Py_None;
  double *e = NULL;
  npy_intp e_Dims[1] = {-1};
  const int e_Rank = 1;
  PyArrayObject *capi_e_tmp = NULL;
  int capi_e_intent = 0;
    static char *capi_kwlist[] = {"p1","p2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:remap.mid_pt3_cart",\
        capi_kwlist,&p1_capi,&p2_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable p1 */
  p1_Dims[0]=3;
  capi_p1_intent |= F2PY_INTENT_IN;
  capi_p1_tmp = array_from_pyobj(NPY_DOUBLE,p1_Dims,p1_Rank,capi_p1_intent,p1_capi);
  if (capi_p1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `p1' of remap.mid_pt3_cart to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p1 = (double *)(PyArray_DATA(capi_p1_tmp));

  /* Processing variable p2 */
  p2_Dims[0]=3;
  capi_p2_intent |= F2PY_INTENT_IN;
  capi_p2_tmp = array_from_pyobj(NPY_DOUBLE,p2_Dims,p2_Rank,capi_p2_intent,p2_capi);
  if (capi_p2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `p2' of remap.mid_pt3_cart to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p2 = (double *)(PyArray_DATA(capi_p2_tmp));

  /* Processing variable e */
  e_Dims[0]=3;
  capi_e_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_e_tmp = array_from_pyobj(NPY_DOUBLE,e_Dims,e_Rank,capi_e_intent,Py_None);
  if (capi_e_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting hidden `e' of remap.mid_pt3_cart to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    e = (double *)(PyArray_DATA(capi_e_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(p1,p2,e);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_e_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_e_tmp == NULL) ... else of e*/
  /* End of cleaning variable e */
  if((PyObject *)capi_p2_tmp!=p2_capi) {
    Py_XDECREF(capi_p2_tmp); }
  }  /*if (capi_p2_tmp == NULL) ... else of p2*/
  /* End of cleaning variable p2 */
  if((PyObject *)capi_p1_tmp!=p1_capi) {
    Py_XDECREF(capi_p1_tmp); }
  }  /*if (capi_p1_tmp == NULL) ... else of p1*/
  /* End of cleaning variable p1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of mid_pt3_cart ****************************/

/******************************* cart_to_latlon *******************************/
static char doc_f2py_rout_remap_cart_to_latlon[] = "\
cart_to_latlon(q,xs,ys,[np])\n\nWrapper for ``cart_to_latlon``.\
\n\nParameters\n----------\n"
"q : in/output rank-2 array('d') with bounds (3,np)\n"
"xs : in/output rank-1 array('d') with bounds (np)\n"
"ys : in/output rank-1 array('d') with bounds (np)\n"
"\nOther Parameters\n----------------\n"
"np : input int, optional\n    Default: shape(q,1)";
/* extern void F_FUNC_US(cart_to_latlon,CART_TO_LATLON)(int*,double*,double*,double*); */
static PyObject *f2py_rout_remap_cart_to_latlon(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int np = 0;
  PyObject *np_capi = Py_None;
  double *q = NULL;
  npy_intp q_Dims[2] = {-1, -1};
  const int q_Rank = 2;
  PyArrayObject *capi_q_tmp = NULL;
  int capi_q_intent = 0;
  PyObject *q_capi = Py_None;
  double *xs = NULL;
  npy_intp xs_Dims[1] = {-1};
  const int xs_Rank = 1;
  PyArrayObject *capi_xs_tmp = NULL;
  int capi_xs_intent = 0;
  PyObject *xs_capi = Py_None;
  double *ys = NULL;
  npy_intp ys_Dims[1] = {-1};
  const int ys_Rank = 1;
  PyArrayObject *capi_ys_tmp = NULL;
  int capi_ys_intent = 0;
  PyObject *ys_capi = Py_None;
    static char *capi_kwlist[] = {"q","xs","ys","np",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:remap.cart_to_latlon",\
        capi_kwlist,&q_capi,&xs_capi,&ys_capi,&np_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable q */
  q_Dims[0]=3;
  capi_q_intent |= F2PY_INTENT_INOUT;
  capi_q_tmp = array_from_pyobj(NPY_DOUBLE,q_Dims,q_Rank,capi_q_intent,q_capi);
  if (capi_q_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 1st argument `q' of remap.cart_to_latlon to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    q = (double *)(PyArray_DATA(capi_q_tmp));

  /* Processing variable np */
  if (np_capi == Py_None) np = shape(q,1); else
    f2py_success = int_from_pyobj(&np,np_capi,"remap.cart_to_latlon() 1st keyword (np) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(q,1)==np,"shape(q,1)==np","1st keyword np","cart_to_latlon:np=%d",np) {
  /* Processing variable xs */
  xs_Dims[0]=np;
  capi_xs_intent |= F2PY_INTENT_INOUT;
  capi_xs_tmp = array_from_pyobj(NPY_DOUBLE,xs_Dims,xs_Rank,capi_xs_intent,xs_capi);
  if (capi_xs_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 2nd argument `xs' of remap.cart_to_latlon to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    xs = (double *)(PyArray_DATA(capi_xs_tmp));

  /* Processing variable ys */
  ys_Dims[0]=np;
  capi_ys_intent |= F2PY_INTENT_INOUT;
  capi_ys_tmp = array_from_pyobj(NPY_DOUBLE,ys_Dims,ys_Rank,capi_ys_intent,ys_capi);
  if (capi_ys_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : remap_error,"failed in converting 3rd argument `ys' of remap.cart_to_latlon to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    ys = (double *)(PyArray_DATA(capi_ys_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&np,q,xs,ys);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ys_tmp!=ys_capi) {
    Py_XDECREF(capi_ys_tmp); }
  }  /*if (capi_ys_tmp == NULL) ... else of ys*/
  /* End of cleaning variable ys */
  if((PyObject *)capi_xs_tmp!=xs_capi) {
    Py_XDECREF(capi_xs_tmp); }
  }  /*if (capi_xs_tmp == NULL) ... else of xs*/
  /* End of cleaning variable xs */
  } /*CHECKSCALAR(shape(q,1)==np)*/
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_q_tmp!=q_capi) {
    Py_XDECREF(capi_q_tmp); }
  }  /*if (capi_q_tmp == NULL) ... else of q*/
  /* End of cleaning variable q */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of cart_to_latlon ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"main",-1,{{-1}},0,(char *)F_FUNC(main,MAIN),(f2py_init_func)f2py_rout_remap_main,doc_f2py_rout_remap_main},
  {"inner_prod",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(inner_prod,INNER_PROD),(f2py_init_func)f2py_rout_remap_inner_prod,doc_f2py_rout_remap_inner_prod},
  {"mid_pt_sphere",-1,{{-1}},0,(char *)F_FUNC_US(mid_pt_sphere,MID_PT_SPHERE),(f2py_init_func)f2py_rout_remap_mid_pt_sphere,doc_f2py_rout_remap_mid_pt_sphere},
  {"get_unit_vect2",-1,{{-1}},0,(char *)F_FUNC_US(get_unit_vect2,GET_UNIT_VECT2),(f2py_init_func)f2py_rout_remap_get_unit_vect2,doc_f2py_rout_remap_get_unit_vect2},
  {"get_latlon_vector",-1,{{-1}},0,(char *)F_FUNC_US(get_latlon_vector,GET_LATLON_VECTOR),(f2py_init_func)f2py_rout_remap_get_latlon_vector,doc_f2py_rout_remap_get_latlon_vector},
  {"normalize_vect",-1,{{-1}},0,(char *)F_FUNC_US(normalize_vect,NORMALIZE_VECT),(f2py_init_func)f2py_rout_remap_normalize_vect,doc_f2py_rout_remap_normalize_vect},
  {"vect_cross",-1,{{-1}},0,(char *)F_FUNC_US(vect_cross,VECT_CROSS),(f2py_init_func)f2py_rout_remap_vect_cross,doc_f2py_rout_remap_vect_cross},
  {"latlon2xyz",-1,{{-1}},0,(char *)F_FUNC(latlon2xyz,LATLON2XYZ),(f2py_init_func)f2py_rout_remap_latlon2xyz,doc_f2py_rout_remap_latlon2xyz},
  {"mid_pt3_cart",-1,{{-1}},0,(char *)F_FUNC_US(mid_pt3_cart,MID_PT3_CART),(f2py_init_func)f2py_rout_remap_mid_pt3_cart,doc_f2py_rout_remap_mid_pt3_cart},
  {"cart_to_latlon",-1,{{-1}},0,(char *)F_FUNC_US(cart_to_latlon,CART_TO_LATLON),(f2py_init_func)f2py_rout_remap_cart_to_latlon,doc_f2py_rout_remap_cart_to_latlon},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "remap",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_remap(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = remap_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module remap (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'remap' is auto-generated with f2py (version:2).\nFunctions:\n"
"  main(geolon_s,geolat_s,geolon_w,geolat_w,is,ie,js,je,u_s,v_s,u_w,v_w,ud,vd)\n"
"  inner_prod = inner_prod(v1,v2)\n"
"  pm = mid_pt_sphere(p1,p2)\n"
"  uc = get_unit_vect2(e1,e2)\n"
"  elon,elat = get_latlon_vector(pp)\n"
"  normalize_vect(e)\n"
"  e = vect_cross(p1,p2)\n"
"  e = latlon2xyz(p,id=)\n"
"  e = mid_pt3_cart(p1,p2)\n"
"  cart_to_latlon(q,xs,ys,np=shape(q,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.20.1");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  remap_error = PyErr_NewException ("remap.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_remap_error", remap_error);
  Py_DECREF(remap_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }


    {
      extern double F_FUNC_US(inner_prod,INNER_PROD)(void);
      PyObject* o = PyDict_GetItemString(d,"inner_prod");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(inner_prod,INNER_PROD),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("inner_prod");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"remap");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
